name: Playwright Tests
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.0-jammy
#    strategy:
#      fail-fast: false
#      matrix:
#        shardIndex: [ 1, 2 ]
#        shardTotal: [ 2 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: CI=true npm run e2e
#        run: CI=true npx playwright test -c test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload playwright blob report to Artifacts
        uses: actions/upload-artifact@v3 #v4 doesn't work, because same name artifacts cannot be uploaded from multiple jobs
        if: always()
        with:
          name: blob-report
          path: blob-report
          retention-days: 30

      - name: Upload nyc report to Artifacts
        uses: actions/upload-artifact@v3 #v4 doesn't work, because same name artifacts cannot be uploaded from multiple jobs
        if: always()
        with:
          name: e2e_nyc_output
          path: e2e_nyc_output
          retention-days: 30

  merge-html-report:    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Merge HTML Reports
    needs: [ e2e-test ]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: npm i

      - name: Download blob reports from Previous job(s)
        uses: actions/download-artifact@v3
        with:
          name: blob-report
          path: all-blob-results

      - name: Generate HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-results

      - name: Upload playwright report to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Download nyc reports from Previous job(s)
        uses: actions/download-artifact@v3
        with:
          name: e2e_nyc_output
          path: e2e_nyc_output

      - name: Generate NYC coverage report
        run: npm run coverage-report

      - name: Upload playwright code coverage to Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-e2e
          path: coverage-e2e/lcov-report
          retention-days: 30

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: coverage-e2e/lcov-report

      - name: Deploy Playwright result to Github Pages
        if: always()
        id: code-coverage
        uses: actions/deploy-pages@v2

      - name: update job summary
        if: always()
        run: echo "# Deployed playwright code coverage result to ${{ steps.code-coverage.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
