name: Playwright Tests
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.0-jammy
#    strategy:
#      fail-fast: false
#      matrix:
#        shardIndex: [ 1, 2 ]
#        shardTotal: [ 2 ]
    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: CI=true npm run e2e
#       run: npm run e2e:ci

      - name: Upload playwright blob report to Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blob-report
          path: blob-report
          retention-days: 30

      - name: Upload nyc report row data to Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e_nyc_output
          path: e2e_nyc_output
          retention-days: 30

  playwright-html-report:    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    name: Playwright HTML Report
    needs: [ e2e-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      - name: Download playwright blob report from Previous job(s)
        uses: actions/download-artifact@v4
        with:
          name: blob-report
          path: all-blob-results

      - name: Generate playwright report
        run: npm run playwright-report

      - name: Upload playwright html report to Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

  coverage-html-report:    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    name: Coverage HTML Report
    needs: [ e2e-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      - name: Download nyc report row data from Previous job(s)
        uses: actions/download-artifact@v4
        with:
          name: e2e_nyc_output
          path: e2e_nyc_output

      - name: Generate coverage report
        run: npm run coverage-report

      - name: Upload playwright code coverage to Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-e2e
          path: coverage-e2e
          retention-days: 30

  deploy-coverage-report:    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    name: Deploy Coverage HTML Report to GitHub Page
    needs: [ coverage-html-report ]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download coverage report from Previous job(s)
        uses: actions/download-artifact@v4
        with:
          name: coverage-e2e
          path: coverage-e2e

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload coverage reports artifact to github-page
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage-e2e/lcov-report

      - name: Deploy Playwright result to Github Pages
        if: always()
        id: deploy-coverage-to-github
        uses: actions/deploy-pages@v4

      - name: update job summary
        if: always()
        run: echo "# Deployed playwright code coverage result to ${{ steps.deploy-coverage-to-github.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
